### PR TITLE
Use prop-types package for React-Proptypes.

### PR DESCRIPTION
**Pull request by sladiri**
I am not familiar with Typescript, but the test script fails:
`src/react-free-style.ts(2,28): error TS7016: Could not find a declaration file for module 'prop-type
s'.`

### CODE REVIEW

**Comment by blakeembrey** [comment]
Thanks for the PR! If you install https://www.npmjs.com/package/@types/prop-types, it should cover it. However, I think `prop-types` should be a regular dependency and not a dev dependency. Possibly even a peer dependency? Not sure how React modules normally use `prop-types`.

**Comment by sladiri** [comment]
Hi, I looked at React-Drag&Drop and it has prop-types as dev-dependency ([package.json](https://github.com/react-dnd/react-dnd/blob/master/package.json#L76)), while react-motion and react-redux-form have it as normal dependency.
I am not very sure about where it should go, to be honest, I added where react react-dom were.

**Comment by blakeembrey** [comment]
@sladiri In `react-dnd`, it's not used as a dependency. It's only for the site and examples, so that seems right. It should be a dependency. `react-dom` is a dev dependency because it's only used for tests, and not for the core package.

**Comment by sladiri** [comment]
I am sorry, the PR is getting a conflict now. I added the typings and moved prop-types to normal dependencies. The tests ran fine locally.

**Comment by blakeembrey** [comment]
You need to merge from master and make sure you resolve the conflicts correctly (looks like you've added the old chai version instead of the one from master). I can also resolve in the GitHub UI if you want.

**Comment by sladiri** [comment]
Thank you for the explanation, I was a bit fast, the conflict is solved now. 👍

**Pull request merged**
